# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode7.3
language: objective-c
# cache: cocoapods
# xcode_workspace: Example/CPJSONRPC.xcworkspace
# xcode_scheme: CPJSONRPC-Example
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/CPJSONRPC.xcworkspace -scheme CPJSONRPC-Example -destination 'platform=iOS Simulator,name=iPhone 4s,OS=latest' | xcpretty
- pod lib lint
